
services:
  postgres:
    image: postgres:17
    container_name: postgres
    environment:
      POSTGRES_USER: postgres     
      POSTGRES_PASSWORD: admin 
      POSTGRES_DB: postgres   
      PGDATA: /var/lib/postgresql/data/pgdata 
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data 
    networks:
      - pg_network

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: jojoweyn@gmail.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    networks:
      - pg_network

volumes:
  postgres_data:

networks:
  pg_network: